joint_state_controller:
  type: joint_state_controller/JointStateController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  publish_rate: 50  

